// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hewvsoagxgqeglzssldx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhld3Zzb2FneGdxZWdsenNzbGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzIzNzgsImV4cCI6MjA2NzQwODM3OH0.rgj_3OfbGBzFmOO0sGS1fpxmJ2i9DP9k0n-8v8WNECM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});